"""migration

Revision ID: 8b95152561db
Revises: b14710bdbb66
Create Date: 2018-10-18 11:54:45.347043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b95152561db'
down_revision = 'b14710bdbb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('dislike', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('like', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'like')
    op.drop_column('pitches', 'dislike')
    # ### end Alembic commands ###
